export const productType = {
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_TO_FAVOURITE: 'ADD_TO_FAVOURITE',
    REMOVE_FROM_FAVOURITE: "REMOVE_FROM_FAVOURITE",
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CHECKOUT: 'CHECKOUT',
    GET_SINGLE_PRODUCT: 'GET_SINGLE_PRODUCT',
    GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
    DELETE_A_PRODUCT: 'DELETE_A_PRODUCT'
  } 